'''

Even Fibonacci Numbers
======================

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''
import time

start = time.time()

max = 4000000

fibonacci = [1,2]

while True:
    n_1, n = fibonacci[-2:]

    if(n_1 + n >= max):
        break

    fibonacci.append(n_1 + n)

print " An: %s" % sum([x for x in fibonacci if x % 2 == 0])

print " in: %ss " % (time.time() - start)
