'''

Highly divisible triangular number
===========================

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

'''
from problem import Problem
from math import sqrt

class Pe012(Problem):
    def __init__(self):
        self.primes = [2]

        self.divs = {}

    def add_factor(self, factor, factors):
        if factor in factors:
            factors[factor] += 1
        else:
            factors[factor] = 1

    def calculate_factors(self, num, factors):
        if(self.isPrime(num)):
            factors[num] = 1
            return

        for i in self.primes:
            if num % i == 0:
                self.add_factor(i, factors)
                if self.isPrime(num / i):
                    self.add_factor(num / i, factors)
                else:
                    self.calculate_factors(num / i, factors)
                break

    def isPrime(self, num):
        i = 3

        if num in self.primes:
            return True

        while i <= num:
            if self._isPrime(i):
                self.primes.append(i)

            i += 2

        return self.primes[-1:][0] == num

    def _isPrime(self, num):
        for i in self.primes:
            if num % i == 0:
                return False

        return True

    def divisors(self, num):
        factors = {}

        self.calculate_factors(num, factors)

        return reduce(lambda x, y: x * y, map(lambda x: x + 1, factors.values()))

    def execute(self):
        num = 0
        divs = []

        highest = (0,0,0)

        for i in range(2, 1000):
            num = i

            divs = self.divisors(num)

            if divs > highest[2]:
                highest = (i, num, divs)
                print highest

            if divs >= 500:
                return str(('v', i, num, divs))

        return str(highest)

Pe012().execute()

#print p.isPrime(2)
#print Pe012().divisors(29)
